### ISSUE TITLE
Unable to send message to workjs

### ISSUE THREAD

**Issue by mao437303994** [vnniz/isolates_helper#1]
Flutter 3.10.6
Dart  3.0.6
isolates_helper 0.3.0
![微信图片_20230719221214](https://github.com/vnniz/isolates_helper/assets/28644312/dbb9e9c3-7dc1-4908-a76b-ce1d43998b20)
The type of 'message' is a 'list', which contains a function that cannot be sent to workjs. Dartsdk will throw an error message 'structured clone of other type'.

**Comment by vnniz** [comment]
Hi @mao437303994

Could you give me a small code that reproduces this issue?

It's a little bit complicated when using Worker because Dart and JS have different kinds of types. So we need to test a few ways to get the expected result.

For instance, if you want to execute a function through Worker, you can use something like below:

``` dart
Function<int> execute(List<String> params) async {
    final String functionName = params[0];
    switch (functionName) {
         case 'add':
              return add(params[1], params[2]);
         ....
   }
}
```

It's better to convert everything to primitive type (String, num, bool, List<String>, Map<String, String>...) before sending it to Worker.

**Comment by mao437303994** [comment]
@vnniz  
Unable to execute normally, the problem lies in the area I just mentioned
https://github.com/mao437303994/test.git

**Comment by vnniz** [comment]
Hi @mao437303994 

I just took a look at your test repo, the best way to do that is using [isolate_manager](https://pub.dev/packages/isolate_manager) which is designed to use for a specific function. Here is an example that serves your purpose:

```dart
// Create the instance
final isolateManager = IsolateManager.create(
  add,
  workerName: 'worker',
);

// counter method
void _incrementCounter() {
    isolateManager.compute(_counter).then((value) {
       setState(() {
          _counter = value;
       });
    });
}
```
